### ISSUE TITLE
Misadvertization

### ISSUE THREAD

**Issue by SuperKnux** [polina4096/resquake#1]
On Modrinth, it states that the mod can be from 1.19 to 1.19.4. But the versions here are only for 1.19.4. Could you either backport to all main versions of 1.19 or remove the incorrect version stating on Modrinth?

**Comment by polina4096** [comment]
Oh well, you are right.

I'm not sure why Modrinth automatically decided that this mod supports all the versions from 1.19 to 1.19.4, as I didn't explicitly set them on the page - the site does tag the versions automatically based on `fabic.mod.json` or some other way.

Are you actually interested in a backport of the mod? I removed unsupported versions from the Modrinth page, but please do reopen this issue if you wish to have this mod available for older versions as well.

**Comment by polina4096** [comment]
It was easy to port it all the way down to 1.19.2, but I'm not sure I want to backport it any further.
