### ISSUE TITLE
[suggestion] Add config option to have the mod enabled by default

### ISSUE THREAD

**Issue by Nicodemus111** [polina4096/resquake#12]

**Comment by polina4096** [comment]
Not sure I understand what do you mean. The mod is enabled by default from the initial installation.

**Comment by Nicodemus111** [comment]
I am asking for an option in the config to have the squake movement toggle enabled when launching the game. Currently it defaults to off when you launch the game and you have to press the keybind to enable it.

**Comment by polina4096** [comment]
I've just installed the mod and it's enabled by default. It must be something wrong with your setup.

**Comment by Nicodemus111** [comment]
Apparently it was set to disabled, oops
