### ISSUE TITLE
Support for Ad Astra gravity

### ISSUE THREAD

**Issue by NolanHewitt** [polina4096/resquake#13]
Currently while using this mod the custom gravity on ad astra planets breaks and reverts to normal gravity. Is there any way this mod could be updated to work with other mods that have varying gravity values? If not, could there be a way to disable resquake movement only while in certain custom dimensions?

**Comment by polina4096** [comment]
sure, i'll look into it

**Comment by NolanHewitt** [comment]
Thank you, I appreciate your work on continuing this mod. Even if the solution just has to be a way to blacklist certain dimensions. After all, it would make some sense that steve wouldn’t be able to make the crazy movements he makes with this mod on a place with gravity as different as the moon.

**Comment by NolanHewitt** [comment]
I've also noticed the same thing happens with the mod Eden Ring. Its custom gravity effects don't work with this mod, but do when you use the hotkey to disable quake movement.

**Comment by polina4096** [comment]
While it is technically possible to add support for every mod, both Ad Astra and Elden Ring Mod mixin into `travel`, which is exactly the how this mod works and why they are incompatible.

In case of the Elden Ring Mod it modifies the gravitational constant in the `LivingEntity`'s `travel`. I can hardcode a fix, but a better solution would of course be to open an issue on the Elden Ring Mod repo and discuss better solutions there.

As for Ad Astra, they inject their movement code at the start of `travel` which is completely incompatible with how my mod works. I think that the best approach for me is to use the Ad Astra Gravity API and incorporate support for it into my mod.

**Comment by NolanHewitt** [comment]
Thank you for the update! Does botania do something similar for movement speed for its items that stop working with this mod active, a mixin for travel?
