### ISSUE TITLE
Cannot move while crawling

### ISSUE THREAD

**Issue by Nicodemus111** [polina4096/resquake#15]

**Comment by Nicodemus111** [comment]
I'm using this on forge 1.20.1-47.1.3 with sinytra 1.0.0-beta.27+1.20.1, forgified fabric api 0.91.0+1.10.4+1.20.1, it lets me move while crawling when squake is disabled so I'm not sure what else could be causing it.

**Comment by NolanHewitt** [comment]
Some mods will have bugs while using the sinytra connector

**Comment by polina4096** [comment]
Oops, that's fixed now.
