### ISSUE TITLE
Update to 1.20.6

### ISSUE THREAD

**Issue by LukaTV939** [polina4096/resquake#18]
Getting this crash report when joining a world/server https://mclo.gs/XrEvvCS

**Comment by polina4096** [comment]
Do you need a 1.20.6 version or is it fine to just release a 1.21?

**Comment by LukaTV939** [comment]
> Do you need a 1.20.6 version or is it fine to just release a 1.21 build?

1.21 is fine now that it's out, so no need for 1.20.6

**Comment by LukaTV939** [comment]
also sorry for late response
