### ISSUE TITLE
Client-side only or required server-side?

### ISSUE THREAD

**Issue by SuperKnux** [polina4096/resquake#3]
Title is self-explanatory. Cool that the mod's 1.19.2 now but, it crashes on server with classnotfound exceptions detailing the client missing, and works fine on client. Following that logic, I'm guessing it's client-side only?

**Comment by polina4096** [comment]
The mod shouldn't crash when installed on the server so this is indeed a bug.

Thanks for reporting it!

I going to investigate into this further and roll out an update in a few hours. Until then I suggest using this mod on the client only, as it should mostly work just fine if you don't have any anti-cheat measures installed on the server.

**Comment by polina4096** [comment]
Closed with the release of version 1.1.0, should work fine on both client and server.

It is actually recommended to install it on both sides to prevent fall damage from slowing the player down.
