### ISSUE TITLE
Underwater movement is broken since 1.1.0

### ISSUE THREAD

**Issue by CreepahJacket** [polina4096/resquake#4]
i've been trying this mod out and thought it was pretty neat, but i've encountered a bug which is seemingly not present in the previous version (1.0.4). 
for some reason, when you're underwater (with sharking enabled), you just float around?? like gravity isn't affected, you also glide around when moving. additionally, with sharking disabled, it acts as if you're on the ground, but jumping is disabled. swimming is entirely fine though, it seems.
i tested this on both 1.19.4 and 1.19.2/3, and they're both bugged.

**Comment by polina4096** [comment]
Not sure how did I manage to miss such an issue. Should be resolved with version 1.1.1, thanks for reporting!
